### ISSUE TITLE
pixels

### ISSUE THREAD

**Issue by vasilisvg** [Wesleyvd/CSS-to-the-Rescue#3]
Lea Verou legt in Hoofdstuk 1 uit dat je beter relative units kunt gebruiken. Lees het nog even na.
https://github.com/Wesleyvd/CSS-to-the-Rescue/blob/master/static/css/style.css#L105

**Comment by vasilisvg** [comment]
Dat geldt zeker ook voor je mediaqueries: https://github.com/Wesleyvd/CSS-to-the-Rescue/blob/master/static/css/style.css#L141

**Comment by Wesleyvd** [comment]
done
