### ISSUE TITLE
Waar zit de target?

### ISSUE THREAD

**Issue by vasilisvg** [Wesleyvd/CSS-to-the-Rescue#6]
Ik zie de target wel in de CSS, maar ik weet niet hoe ik hem te zien krijg in de browser. Waar moet ik op klikken?

**Comment by Wesleyvd** [comment]
De target zit op het (edit) gedeelte bij de soort van 'over mij'  tekst aan het begin, dan komt er een pop up op waar de achtergrond de-emphesized

**Comment by vasilisvg** [comment]
Mooie de-emphasize! Thanks! Die edit-knop is wel heel erg goed verstopt. Als je graag wil dat niemand ooit op die link klikt dan moet je hem zo vormgeven (-:
